<?php 
/*
 * DigitalNewzealandLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/27/2016
 */

namespace DigitalNewzealandLib\Models;

use JsonSerializable;

/**
 * Collection of search Records endpoint
 */
class CollectionSearchRecords implements JsonSerializable {
    /**
     * the value of the num_results parameter sent to the API method
     * @required
     * @maps num_results_requested
     * @var integer $numResultsRequested public property
     */
    public $numResultsRequested;

    /**
     * the total number of results matching this search
     * @required
     * @maps result_count
     * @var integer $resultCount public property
     */
    public $resultCount;

    /**
     * the value of the start parameter sent to the API method
     * @required
     * @var string $start public property
     */
    public $start;

    /**
     * the search results data. The results element will contain 0 or more result elements
     * @required
     * @var ResultsCollection $results public property
     */
    public $results;

    /**
     * the facet result data (if requested). The facets element will contain one facet-field element corresponding to each facet requested. Each facet-field element contains a sorted list of value elements that are made up of a name and num-results element.
     * @required
     * @var array $facets public property
     */
    public $facets;

    /**
     * Constructor to set initial or default values of member properties
     * @param   integer           $numResultsRequested     Initialization value for the property $this->numResultsRequested  
     * @param   integer           $resultCount             Initialization value for the property $this->resultCount          
     * @param   string            $start                   Initialization value for the property $this->start                
     * @param   ResultsCollection   $results                 Initialization value for the property $this->results              
     * @param   array             $facets                  Initialization value for the property $this->facets               
     */
    public function __construct()
    {
        if(5 == func_num_args())
        {
            $this->numResultsRequested   = func_get_arg(0);
            $this->resultCount           = func_get_arg(1);
            $this->start                 = func_get_arg(2);
            $this->results               = func_get_arg(3);
            $this->facets                = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['num_results_requested'] = $this->numResultsRequested;
        $json['result_count']          = $this->resultCount;
        $json['start']                 = $this->start;
        $json['results']               = $this->results;
        $json['facets']                = $this->facets;

        return $json;
    }
}