<?php 
/*
 * DigitalNewzealandLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/27/2016
 */

namespace DigitalNewzealandLib\Models;

use JsonSerializable;

/**
 * Results collection 
 */
class ResultsCollection implements JsonSerializable {
    /**
     * this record is licensed for commercial use
     * @required
     * @maps is_commercial_use
     * @var bool $isCommercialUse public property
     */
    public $isCommercialUse;

    /**
     * a string containing one or more category names separated by a comma (e.g. Images, Web pages)
     * @required
     * @var string $category public property
     */
    public $category;

    /**
     * the institution holding the content to which the record refers
     * @required
     * @maps content_partner
     * @var string $contentPartner public property
     */
    public $contentPartner;

    /**
     * text describing the record
     * @required
     * @var string $description public property
     */
    public $description;

    /**
     * additional text describing the record
     * @required
     * @maps additional_description
     * @var string $additionalDescription public property
     */
    public $additionalDescription;

    /**
     * the url for the content on the contentpartner's website. Please use the source_url when providing HTML links (see below)
     * @required
     * @maps landing_url
     * @var string $landingUrl public property
     */
    public $landingUrl;

    /**
     * the internal DigitalNZ identifier (used by the Get Metadata API)
     * @required
     * @var string $id public property
     */
    public $id;

    /**
     * the url that will redirect users to the landing_url. By using this link (as opposed to the display_url) we are able to count clickthroughs which is helpful for demonstrating the value of DigitalNZ
     * @required
     * @maps source_url
     * @var string $sourceUrl public property
     */
    public $sourceUrl;

    /**
     * the date the record was added to DigitalNZ
     * @required
     * @maps syndication_date
     * @var string $syndicationDate public property
     */
    public $syndicationDate;

    /**
     * the url of for a thumbnail image of the content to which the record refers. This field may be empty.
     * @required
     * @maps thumbnail_url
     * @var string $thumbnailUrl public property
     */
    public $thumbnailUrl;

    /**
     * the title of the record
     * @required
     * @var string $title public property
     */
    public $title;

    /**
     * The latitude and longitude in the following format: namespace:lat,long; Multiple values are seperated by semi-colons, for example: namespace:lat,long;namespace:lat,long;namespace:lat,long; NOTE: namespace is optional.
     * @required
     * @maps geo_co_ords
     * @var string $geoCoOrds public property
     */
    public $geoCoOrds;

    /**
     * a larger thumbnail image with dimensions up to 800px (NB the API Terms do not extend rights to the use of these thumbnails)
     * @required
     * @maps large_thumbnail_url
     * @var string $largeThumbnailUrl public property
     */
    public $largeThumbnailUrl;

    /**
     * the url of the object licence. This field may be empty.
     * @required
     * @maps rights_url
     * @var string $rightsUrl public property
     */
    public $rightsUrl;

    /**
     * string with date information in multiple, often unstructured formats (e.g. Circa 2000)
     * @required
     * @maps display_date
     * @var string $displayDate public property
     */
    public $displayDate;

    /**
     * boolean, associated with research paper items. True indicates the research paper has been peer reviewed
     * @required
     * @maps peer_reviewed
     * @var bool $peerReviewed public property
     */
    public $peerReviewed;

    /**
     * a number indicating the field of research
     * @required
     * @maps marsden_code
     * @var integer $marsdenCode public property
     */
    public $marsdenCode;

    /**
     * lists the author's names
     * @required
     * @var string $author public property
     */
    public $author;

    /**
     * boolean value, if set to true it indicates the item doesn't have an external landing page, usually because it is a downloadable item such as a pdf or mpeg
     * @required
     * @maps no_landing_page
     * @var bool $noLandingPage public property
     */
    public $noLandingPage;

    /**
     * a url pointing to a downloadable object, i.e. an image, pdf or mpeg
     * @required
     * @maps object_url
     * @var string $objectUrl public property
     */
    public $objectUrl;

    /**
     * list of dates published
     * @required
     * @maps published_date
     * @var string $publishedDate public property
     */
    public $publishedDate;

    /**
     * lists the publisher's names
     * @required
     * @var string $publisher public property
     */
    public $publisher;

    /**
     * Dublin Core categorisation indicating type
     * @required
     * @var string $dctype public property
     */
    public $dctype;

    /**
     * the library collection the item belongs to
     * @required
     * @maps library_collection
     * @var string $libraryCollection public property
     */
    public $libraryCollection;

    /**
     * the display collection the item belongs to
     * @required
     * @maps display_collection
     * @var string $displayCollection public property
     */
    public $displayCollection;

    /**
     * the item's parent collection
     * @required
     * @maps collection_parent
     * @var string $collectionParent public property
     */
    public $collectionParent;

    /**
     * the top level collection
     * @required
     * @maps collection_root
     * @var string $collectionRoot public property
     */
    public $collectionRoot;

    /**
     * a date associated with the record (e.g. 1996-01-01T00:00:00.000Z). This field may be empty
     * @var double $date public property
     */
    public $date;

    /**
     * the copyright statement applying to the object. This field may be empty.
     * @var string $copyright public property
     */
    public $copyright;

    /**
     * the licence for the object. This field may be empty
     * @var string $license public property
     */
    public $license;

    /**
     * Constructor to set initial or default values of member properties
     * @param   bool              $isCommercialUse          Initialization value for the property $this->isCommercialUse       
     * @param   string            $category                 Initialization value for the property $this->category              
     * @param   string            $contentPartner           Initialization value for the property $this->contentPartner        
     * @param   string            $description              Initialization value for the property $this->description           
     * @param   string            $additionalDescription    Initialization value for the property $this->additionalDescription 
     * @param   string            $landingUrl               Initialization value for the property $this->landingUrl            
     * @param   string            $id                       Initialization value for the property $this->id                    
     * @param   string            $sourceUrl                Initialization value for the property $this->sourceUrl             
     * @param   string            $syndicationDate          Initialization value for the property $this->syndicationDate       
     * @param   string            $thumbnailUrl             Initialization value for the property $this->thumbnailUrl          
     * @param   string            $title                    Initialization value for the property $this->title                 
     * @param   string            $geoCoOrds                Initialization value for the property $this->geoCoOrds             
     * @param   string            $largeThumbnailUrl        Initialization value for the property $this->largeThumbnailUrl     
     * @param   string            $rightsUrl                Initialization value for the property $this->rightsUrl             
     * @param   string            $displayDate              Initialization value for the property $this->displayDate           
     * @param   bool              $peerReviewed             Initialization value for the property $this->peerReviewed          
     * @param   integer           $marsdenCode              Initialization value for the property $this->marsdenCode           
     * @param   string            $author                   Initialization value for the property $this->author                
     * @param   bool              $noLandingPage            Initialization value for the property $this->noLandingPage         
     * @param   string            $objectUrl                Initialization value for the property $this->objectUrl             
     * @param   string            $publishedDate            Initialization value for the property $this->publishedDate         
     * @param   string            $publisher                Initialization value for the property $this->publisher             
     * @param   string            $dctype                   Initialization value for the property $this->dctype                
     * @param   string            $libraryCollection        Initialization value for the property $this->libraryCollection     
     * @param   string            $displayCollection        Initialization value for the property $this->displayCollection     
     * @param   string            $collectionParent         Initialization value for the property $this->collectionParent      
     * @param   string            $collectionRoot           Initialization value for the property $this->collectionRoot        
     * @param   double            $date                     Initialization value for the property $this->date                  
     * @param   string            $copyright                Initialization value for the property $this->copyright             
     * @param   string            $license                  Initialization value for the property $this->license               
     */
    public function __construct()
    {
        if(30 == func_num_args())
        {
            $this->isCommercialUse        = func_get_arg(0);
            $this->category               = func_get_arg(1);
            $this->contentPartner         = func_get_arg(2);
            $this->description            = func_get_arg(3);
            $this->additionalDescription  = func_get_arg(4);
            $this->landingUrl             = func_get_arg(5);
            $this->id                     = func_get_arg(6);
            $this->sourceUrl              = func_get_arg(7);
            $this->syndicationDate        = func_get_arg(8);
            $this->thumbnailUrl           = func_get_arg(9);
            $this->title                  = func_get_arg(10);
            $this->geoCoOrds              = func_get_arg(11);
            $this->largeThumbnailUrl      = func_get_arg(12);
            $this->rightsUrl              = func_get_arg(13);
            $this->displayDate            = func_get_arg(14);
            $this->peerReviewed           = func_get_arg(15);
            $this->marsdenCode            = func_get_arg(16);
            $this->author                 = func_get_arg(17);
            $this->noLandingPage          = func_get_arg(18);
            $this->objectUrl              = func_get_arg(19);
            $this->publishedDate          = func_get_arg(20);
            $this->publisher              = func_get_arg(21);
            $this->dctype                 = func_get_arg(22);
            $this->libraryCollection      = func_get_arg(23);
            $this->displayCollection      = func_get_arg(24);
            $this->collectionParent       = func_get_arg(25);
            $this->collectionRoot         = func_get_arg(26);
            $this->date                   = func_get_arg(27);
            $this->copyright              = func_get_arg(28);
            $this->license                = func_get_arg(29);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['is_commercial_use']      = $this->isCommercialUse;
        $json['category']               = $this->category;
        $json['content_partner']        = $this->contentPartner;
        $json['description']            = $this->description;
        $json['additional_description'] = $this->additionalDescription;
        $json['landing_url']            = $this->landingUrl;
        $json['id']                     = $this->id;
        $json['source_url']             = $this->sourceUrl;
        $json['syndication_date']       = $this->syndicationDate;
        $json['thumbnail_url']          = $this->thumbnailUrl;
        $json['title']                  = $this->title;
        $json['geo_co_ords']            = $this->geoCoOrds;
        $json['large_thumbnail_url']    = $this->largeThumbnailUrl;
        $json['rights_url']             = $this->rightsUrl;
        $json['display_date']           = $this->displayDate;
        $json['peer_reviewed']          = $this->peerReviewed;
        $json['marsden_code']           = $this->marsdenCode;
        $json['author']                 = $this->author;
        $json['no_landing_page']        = $this->noLandingPage;
        $json['object_url']             = $this->objectUrl;
        $json['published_date']         = $this->publishedDate;
        $json['publisher']              = $this->publisher;
        $json['dctype']                 = $this->dctype;
        $json['library_collection']     = $this->libraryCollection;
        $json['display_collection']     = $this->displayCollection;
        $json['collection_parent']      = $this->collectionParent;
        $json['collection_root']        = $this->collectionRoot;
        $json['date']                   = $this->date;
        $json['copyright']              = $this->copyright;
        $json['license']                = $this->license;

        return $json;
    }
}