<?php
/*
 * DigitalNewzealandLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/27/2016
 */

namespace DigitalNewzealandLib;

/**
 * All configuration including auth info and base URI for the API access
 * are configured in this class. 
 */
class Configuration {
    /**
     * The base Uri for API calls
     * @var string
     */
    public static $BASEURI = 'http://api.digitalnz.org';

    /**
     * Your API Key
     * @var string
     */
    /**
     * @todo Replace the $apiKey with an appropriate value
     */
    public static $apiKey = '';

}
