<?php
/*
 * DigitalNewzealandLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/27/2016
 */

namespace DigitalNewzealandLib;

use DigitalNewzealandLib\Controllers;

/**
 * DigitalNewzealandLib client class
 */
class DigitalNewzealandClient
{
    /**
     * Constructor with authentication and configuration parameters
     */
    public function __construct($apiKey = NULL)
    {
        Configuration::$apiKey = $apiKey ? $apiKey : Configuration::$apiKey;
    }
 
    /**
     * Singleton access to Metadata controller
     * @return Controllers\MetadataController The *Singleton* instance
     */
    public function getMetadata()
    {
        return Controllers\MetadataController::getInstance();
    }
 
    /**
     * Singleton access to SearchRecord controller
     * @return Controllers\SearchRecordController The *Singleton* instance
     */
    public function getSearchRecord()
    {
        return Controllers\SearchRecordController::getInstance();
    }
}